# Generated by Django 3.1.4 on 2020-12-10 19:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('business_type', models.CharField(max_length=32)),
                ('account_no', models.IntegerField()),
                ('ifsc_code', models.CharField(max_length=12)),
                ('beneficiary_name', models.TextField()),
                ('target_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(100000000)])),
                ('status', models.CharField(max_length=32)),
                ('type', models.CharField(max_length=20)),
                ('pitch', models.TextField()),
                ('reward', models.TextField(blank=True, null=True)),
                ('min_investment', models.FloatField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(1000000)])),
                ('end_date', models.DateTimeField()),
                ('debt_interest', models.FloatField()),
                ('debt_period', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
